### PR TITLE
Fixes #29 - Implementing a timestamps option in Schema option section

### LINKED ISSUE #29: Timestamp fields suport like createdAt and updatedAt
What about have support to createdAt fields and updatedAt fields like others? CreatedAt  automatically saves datetime when record was created and updatedAt a datetime when record was last saved.
This maybe achieved using a New option when a define a schema.

### PR DESCRIPTION
**Pull request by darthapple**
Added support for timestamps attribute in option section of the schema

### CODE REVIEW

**Comment by brandongoode** [comment]
Looks great.

For completeness, would you mind adding test case and updating the Readme?

**Comment by darthapple** [comment]
OK, I'll do this!!

**Comment by darthapple** [comment]
@brandongoode done!!!

**Comment by brandongoode** [comment]
Awesome - Thanks

**Pull request merged**
