### PR TITLE
Support for filter object

### PR DESCRIPTION
**Pull request by asynxis**
Adding support for: 

Dog.scan({breed: {contains: 'Terrier'} }, function (err, dogs) {
  // Look at all the Terriers
});

and small fixes

### CODE REVIEW

**Comment by asynxis** [comment]
I do not know what's the problem with use strict. When I run test on my local - all is fine.
PTAL please.

**Comment by brandongoode** [comment]
Thanks for the PR.  No sure what's up with the use strict either.  I'll dig into it this evening.

**Comment by asynxis** [comment]
Can u please take a look on pull-request?

**Comment by brandongoode** [comment]
Sorry -- I ment to look at this the other day and forgot. 

Noticed a couple of minor correction. The changes to the Readme are not correct.  Also, the JSON.stringify is requried for number types to convert the number to a String (required by DynamoDB).

**Comment by asynxis** [comment]
About Readme.md - please look at line 455 in file test/Model.js

About number converting, please see Attribute.js line 312. There is anyway value converting to string.

Or maybe I get something wrong:)

**Comment by asynxis** [comment]
Actually I removed converting JSON.stringify cause When i do for exmaple scan({foo:'1'}) it convert request to {N:{"'1'"}}

**Comment by brandongoode** [comment]
Ok.  Now I see. You're correct the JSON.stringify needed at all.

**Comment by asynxis** [comment]
Thnx! Can u also bump a new version to npm?

**Comment by brandongoode** [comment]
bumped -- Thanks for the PR

**Pull request merged**
