### PR TITLE
#93 - Adding support for scan.all()

### PR DESCRIPTION
**Pull request by fishcharlie**
This pull request attempts to add support for scan.all() as described in #93. I tried to integrate this with as minimal code changes as possible but there might be a better way to integrate this more cleanly and with less disruption to the code base.

Feel free to discuss and let me know if there is anything else I can do to get this merged in.

### CODE REVIEW

**Comment by brandongoode** [comment]
Thanks for the PR.  It's a great addition.  Give me a few days to look it over.

**Comment by fishcharlie** [comment]
Thanks Brandon. Let me know if I can make any adjustments or updates.

I'm not sure why the tests are failing. I ran the tests locally and they all passed.

I also just realized if for whatever reason options.all gets overwritten to null that will cause problems.

I'm currently on my phone but in a little bit I'll try to look into both isssues and repush if I'm able to come up with fixes.

**Comment by fishcharlie** [comment]
@brandongoode That should fix the undefined issue. Still not sure why tests are failing. Any insight into this would be great. Let me know what other changes or adjustments you need from me when you have a chance to look it over.

**Comment by brandongoode** [comment]
@fishcharlie,  It looks good.  The failure was just a timing issue that happens with TravisCI.  I reran the test, and it's passing now.

Could you add the feature to the Scan section in docs/index.md and some test cases?

**Comment by fishcharlie** [comment]
@brandongoode Just added the documentation. Tried to add 2 unit tests. I'm not the best/most experienced with unit tests. So not sure if they are good tests or anything like that. If someone else wants to write better unit tests feel free since I'm not the best at that haha.

**Comment by brandongoode** [comment]
Thanks.  I'll pull it down and add a few more checks to the test cases.

**Pull request merged**
