### PR TITLE
Allow saving falsey values with saveUnknown

### PR DESCRIPTION
**Pull request by ecwyne**
Addresses #360 

Values of `false`, `''`, and `0` should all be saved without error.

### CODE REVIEW

**Comment by fishcharlie** [comment]
This looks to be a duplicate of #336

**Comment by ecwyne** [comment]
Tests are only failing because of use of `const` keyword in `chalk` on `node v0.12`

**Comment by fishcharlie** [comment]
@ecwyne It actually looks like Chalk is a major problem for other PRs... maybe skipping version 0.9 and going right to 1.0 and removing support for older Node.js version is the way to go. For your use cases what version(s) of Node.js do you require Dynamoose to support? There has been some discussion about what versions of Node.js to support. What are your thoughts on this?

**Comment by ecwyne** [comment]
I'm using `v8.0` on lambda. No need to support older versions from me!

**Pull request closed without merging**
